// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.initial")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.initial")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.signUpUpdate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.signUpUpdate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.signUpUpdate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.signUpUpdate.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.signUp")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.signUp")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.signUp.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1208:System using directives should be placed before other using directives", Justification = "Migration file")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.initial.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.ChangePasswordToken.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Migration file", Scope = "type", Target = "~T:SCCB.Web.Migrations.ChangePasswordToken")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.initial.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.initial.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.signUp.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.signUpUpdate.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Migration file", Scope = "member", Target = "~M:SCCB.Web.Migrations.ChangePasswordToken.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
